### ISSUE TITLE
PRACTICA-LOGICA-PROPOSICIONAL-EQUIPO-EDUARDO-TOMAS-1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-team-eduardo-tomas-1as#1]
[PRÁCTRICA_LOGICA_PROPOSICIONAL_Y_TABLAS DE VERDAD_1AS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-team-eduardo-tomas-1as/files/7530282/PRACTRICA_LOGICA_PROPOSICIONAL_Y_TABLAS.DE.VERDAD_1AS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf)

**Comment by UrielGB10** [comment]
La calificación en la practica es de 26% ya que tiene problemas en su conclusión ,hay que mejorar en ese apartado pero en general la práctica está bien.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
